AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ParallelAssignment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/MixinGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false  