default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: scoutplan_development

test:
  <<: *default
  database: scoutplan_test

production:
  <<: *default
  port: <%= ENV['DATABASE_PORT'] %>