:schedule:
  send_digests:
    # cron: '0 0 * * * *' # every hour
    cron: '0 * * * * *' # every minute
    class: DigestSender

  send_today_reminders:
    cron: '0 * * * * *' # check every minute
    class: DailyReminderSender
