apiVersion: batch/v1
kind: Job
metadata:
  name: scoutplan-db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        command:
        - rails
        - db:migrate
        image: registry.digitalocean.com/scoutplan/app