apiVersion: batch/v1
kind: Job
metadata:
  name: scoutplan-db-migrate
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - rails
        - db:migrate
        image: registry.digitalocean.com/scoutplan/app
